### ISSUE TITLE
提出如下几点

### ISSUE THREAD

**Issue by ariable** [aofall/Gethosts#1]
引用CSS之类文件时的相对路径 如/css/style.css前加个. 不然在非根目录下回出现问题 
包括/help/index.html
背景图片的压缩版本已上传至新浪 
http://ww4.sinaimg.cn/large/4cfccf7ajw1eua8poh2nzj21hc0xc41x.jpg
还有 我习惯把js的引用放在前面

**Comment by aofall** [comment]
已修改
